'use client';

import { useProject } from '@/components/workspace/ProjectContext';
import { CodeEditor } from '@/components/builder/CodeEditor';
import { ReadmeViewer } from '@/components/builder/ReadmeViewer';

export default function ProjectBlueprintPage() {
  const { project } = useProject();

  const readmeContent = project?.readme_code || `# ${project?.name}\n\n${project?.description}\n\nGenerated by Blueprint.ai`;

  return (
    <div className="flex h-full flex-col p-6 space-y-6">
      <div className="border-b border-white/10 pb-4">
        <h1 className="text-2xl font-black text-white">Blueprint Specifications</h1>
        <p className="text-xs text-white/50 mt-1">
          Inspect generated files, database SQL schema, API contracts, and README.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 flex-1 min-h-[500px]">
        <div className="rounded-2xl border border-white/10 bg-[#070a0f] overflow-hidden flex flex-col">
          <CodeEditor title="supabase/schema.sql" fallbackContent={project?.schema_code || '-- PostgreSQL Schema'} />
        </div>
        <div className="rounded-2xl border border-white/10 bg-[#070a0f] overflow-hidden flex flex-col p-4">
          <ReadmeViewer content={readmeContent} />
        </div>
      </div>
    </div>
  );
}
