import { z } from 'zod';
import { projectFileSchema } from './project';

// ── Existing schemas (preserved) ──────────────────────────────────────────────

export const pushGithubSchema = z.object({
  owner: z.string().trim().optional(),
  repoName: z.string().trim().min(1, 'Repository name is required').regex(/^[\w.-]+$/, 'Invalid repository name'),
  isPrivate: z.boolean().default(true),
  commitMessage: z.string().default('feat: initial blueprint commit'),
  branchName: z.string().default('main'),
  files: z.array(projectFileSchema).default([]),
});

export const pullRequestGithubSchema = z.object({
  owner: z.string().trim().min(1, 'Owner is required'),
  repo: z.string().trim().min(1, 'Repository name is required'),
  branchName: z.string().min(1, 'Branch name is required'),
  baseBranch: z.string().default('main'),
  title: z.string().default('feat: AI Blueprint generated updates'),
  body: z.string().default('This pull request was generated by Blueprint.ai.'),
});

// ── New schemas ────────────────────────────────────────────────────────────────

export const connectRepoSchema = z.object({
  projectId: z.string().uuid('Invalid project ID'),
  owner: z.string().trim().min(1, 'Owner is required'),
  repo: z.string().trim().min(1, 'Repository name is required'),
});

export const createBranchSchema = z.object({
  owner: z.string().trim().min(1, 'Owner is required'),
  repo: z.string().trim().min(1, 'Repository name is required'),
  branchName: z
    .string()
    .trim()
    .min(1, 'Branch name is required')
    .regex(/^[\w./-]+$/, 'Invalid branch name characters'),
  fromBranch: z.string().default('main'),
});

export const fetchBranchesSchema = z.object({
  owner: z.string().trim().min(1),
  repo: z.string().trim().min(1),
});

export const fetchCommitsSchema = z.object({
  owner: z.string().trim().min(1),
  repo: z.string().trim().min(1),
  branch: z.string().default('main'),
  per_page: z.coerce.number().int().min(1).max(100).default(30),
});

export const fetchFilesSchema = z.object({
  owner: z.string().trim().min(1),
  repo: z.string().trim().min(1),
  branch: z.string().default('main'),
  path: z.string().default(''),
});

export const fetchDiffSchema = z.object({
  owner: z.string().trim().min(1),
  repo: z.string().trim().min(1),
  base: z.string().default('main'),
  head: z.string().min(1, 'Head branch or SHA is required'),
});

// ── Types ──────────────────────────────────────────────────────────────────────

export type PushGithubInput = z.infer<typeof pushGithubSchema>;
export type PullRequestGithubInput = z.infer<typeof pullRequestGithubSchema>;
export type ConnectRepoInput = z.infer<typeof connectRepoSchema>;
export type CreateBranchInput = z.infer<typeof createBranchSchema>;
export type FetchBranchesInput = z.infer<typeof fetchBranchesSchema>;
export type FetchCommitsInput = z.infer<typeof fetchCommitsSchema>;
export type FetchFilesInput = z.infer<typeof fetchFilesSchema>;
export type FetchDiffInput = z.infer<typeof fetchDiffSchema>;

// ── Response Types (safe for client) ──────────────────────────────────────────

export interface GithubRepo {
  id: number;
  name: string;
  full_name: string;
  owner: string;
  private: boolean;
  description: string | null;
  html_url: string;
  default_branch: string;
  language: string | null;
  stargazers_count: number;
  updated_at: string;
}

export interface GithubBranch {
  name: string;
  sha: string;
  protected: boolean;
}

export interface GithubCommit {
  sha: string;
  message: string;
  author: string;
  authorAvatar: string;
  date: string;
  url: string;
}

export interface GithubFileEntry {
  name: string;
  path: string;
  type: 'file' | 'dir';
  sha: string;
  size: number;
  url: string;
}

export interface GithubDiffFile {
  filename: string;
  status: 'added' | 'removed' | 'modified' | 'renamed';
  additions: number;
  deletions: number;
  changes: number;
  patch?: string;
}

export interface GithubPullRequest {
  number: number;
  title: string;
  html_url: string;
  state: 'open' | 'closed' | 'merged';
  head: string;
  base: string;
  created_at: string;
}
